spring.application.name=ChromaDress
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

python.service.url=${ANALYSIS_SERVICE_URL:http://localhost:5000}

app.upload.dir=${UPLOAD_DIR:uploads/clothing/}
app.upload.base-url=${APP_BASE_URL:http://localhost:8080}/uploads/clothing/

jwt.secret=${JWT_SECRET:SLc+ET5k58pptjMOBfwG/Bl80vaAPHfdFTMxYKMzNGE=}
jwt.access-token-expiration=15m
jwt.refresh-token-expiration=7d

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chroma_dress_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}