python.service.url=http://localhost:5000
app.upload.dir=uploads/clothing/
app.upload.base-url=http://localhost:8080/uploads/clothing/
jwt.secret=QuestaEUnaChiaveSegretaMoltoLungaPerSuperareIControlliDiSicurezza2026
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

