python.service.url=http://localhost:5000
app.upload.dir=/var/www/chromadress/uplaods/
app.upload.base-url=https://api.chromadress.com/uploads/
jwt.secret=una_chiave_segreta_molto_lunga_almeno_32_caratteri_per_chroma
spring.datasource.url=jdbc:postgresql://localhost:5432/chroma_dress_db